name: Metrics
on:
  # Schedule daily updates
  # schedule: [{cron: "15 0/3 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  votd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install @glowstudent/youversion
      - name: Build dependencies
        run: npm run build
