name: Verse of the Day
on:
  # Schedule daily updates
  # schedule: [{cron: "15 0/3 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}

jobs:
  votd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Build dependencies
        run: npm run build
      - name: Get Verse of the Day 
        id: get_verse
        run: |
          verse=$(npm run serve)
          echo "image_url=$verse" >> $GITHUB_OUTPUT
      - name: Download Image
        uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9
        with:
          url: "${{ steps.get_verse.outputs.image_url }}"
          target: assets
          auto-match: true
          filename: "votd.jpg"
